# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: ë¬¸ì˜í•˜ê¸°
    url: https://github.com/JANGSEYEONG/DalSongPyeonji/issues/new
    about: ì¶”ê°€ì ì¸ ë¬¸ì˜ ì‚¬í•­ì´ ìˆìœ¼ë©´ ì´ê³³ì„ í´ë¦­í•˜ì„¸ìš”.
issue_templates:
  - name: ë²„ê·¸ ë¦¬í¬íŠ¸
    description: í”„ë¡œì íŠ¸ ê°œì„ ì„ ìœ„í•´ ë²„ê·¸ë¥¼ ì‹ ê³ í•´ì£¼ì„¸ìš”.
    title: 'ğŸ [ë²„ê·¸] ì œëª©ì„ ì…ë ¥í•˜ì„¸ìš”'
    labels: bug
    assignees: ''
    template: bug_report.md
  - name: ê¸°ëŠ¥ ìš”ì²­
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ì„ ì œì•ˆí•´ì£¼ì„¸ìš”.
    title: 'âœ¨ [ê¸°ëŠ¥] ì œëª©ì„ ì…ë ¥í•˜ì„¸ìš”'
    labels: enhancement
    assignees: ''
    template: feature_request.md
